// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sportiverse/sportiverse/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the sportiverse module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params            Params         `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PostList          []Post         `protobuf:"bytes,2,rep,name=postList,proto3" json:"postList"`
	PostCount         uint64         `protobuf:"varint,3,opt,name=postCount,proto3" json:"postCount,omitempty"`
	CommentList       []Comment      `protobuf:"bytes,4,rep,name=commentList,proto3" json:"commentList"`
	CommentCount      uint64         `protobuf:"varint,5,opt,name=commentCount,proto3" json:"commentCount,omitempty"`
	SubscriptionList  []Subscription `protobuf:"bytes,6,rep,name=subscriptionList,proto3" json:"subscriptionList"`
	SubscriptionCount uint64         `protobuf:"varint,7,opt,name=subscriptionCount,proto3" json:"subscriptionCount,omitempty"`
	LikeList          []Like         `protobuf:"bytes,8,rep,name=likeList,proto3" json:"likeList"`
	LikeCount         uint64         `protobuf:"varint,9,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	AccountList       []Account      `protobuf:"bytes,10,rep,name=accountList,proto3" json:"accountList"`
	AccountCount      uint64         `protobuf:"varint,11,opt,name=accountCount,proto3" json:"accountCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_18bb63232aac3f3b, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPostList() []Post {
	if m != nil {
		return m.PostList
	}
	return nil
}

func (m *GenesisState) GetPostCount() uint64 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *GenesisState) GetCommentList() []Comment {
	if m != nil {
		return m.CommentList
	}
	return nil
}

func (m *GenesisState) GetCommentCount() uint64 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *GenesisState) GetSubscriptionList() []Subscription {
	if m != nil {
		return m.SubscriptionList
	}
	return nil
}

func (m *GenesisState) GetSubscriptionCount() uint64 {
	if m != nil {
		return m.SubscriptionCount
	}
	return 0
}

func (m *GenesisState) GetLikeList() []Like {
	if m != nil {
		return m.LikeList
	}
	return nil
}

func (m *GenesisState) GetLikeCount() uint64 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *GenesisState) GetAccountList() []Account {
	if m != nil {
		return m.AccountList
	}
	return nil
}

func (m *GenesisState) GetAccountCount() uint64 {
	if m != nil {
		return m.AccountCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "sportiverse.sportiverse.GenesisState")
}

func init() {
	proto.RegisterFile("sportiverse/sportiverse/genesis.proto", fileDescriptor_18bb63232aac3f3b)
}

var fileDescriptor_18bb63232aac3f3b = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6a, 0xea, 0x40,
	0x14, 0xc6, 0x93, 0x6b, 0xae, 0x57, 0x27, 0x2e, 0xae, 0xc3, 0x85, 0x2b, 0x72, 0x6f, 0x0c, 0x72,
	0x05, 0x91, 0x4b, 0x04, 0xbb, 0xea, 0xaa, 0x34, 0x2e, 0xda, 0x85, 0x8b, 0xa2, 0x8b, 0x42, 0x77,
	0x31, 0x0c, 0x32, 0xd8, 0x64, 0x42, 0x66, 0x2c, 0xed, 0x5b, 0xf4, 0x31, 0xba, 0xec, 0x63, 0xb8,
	0x74, 0xd9, 0x55, 0x29, 0xba, 0xe8, 0x03, 0xf4, 0x05, 0xca, 0xfc, 0x89, 0x1d, 0x91, 0x21, 0x9b,
	0x70, 0xe6, 0xcc, 0x77, 0xce, 0xef, 0xe4, 0x9b, 0x03, 0x7a, 0x34, 0x23, 0x39, 0xc3, 0x77, 0x28,
	0xa7, 0x68, 0xa8, 0xc7, 0x0b, 0x94, 0x22, 0x8a, 0x69, 0x90, 0xe5, 0x84, 0x11, 0xf8, 0x5b, 0xbb,
	0x0a, 0xb4, 0xb8, 0xdd, 0x8c, 0x12, 0x9c, 0x92, 0xa1, 0xf8, 0x4a, 0x6d, 0xfb, 0xd7, 0x82, 0x2c,
	0x88, 0x08, 0x87, 0x3c, 0x52, 0xd9, 0x7f, 0x26, 0x50, 0x16, 0xe5, 0x51, 0xa2, 0x38, 0xed, 0xae,
	0x51, 0x45, 0x28, 0x53, 0x1a, 0xe3, 0xc8, 0x31, 0x49, 0x12, 0x94, 0x16, 0xb2, 0x81, 0x49, 0x46,
	0x57, 0x73, 0x1a, 0xe7, 0x38, 0x63, 0x98, 0xa4, 0x65, 0xd8, 0x5b, 0xbc, 0x44, 0x65, 0xd8, 0x28,
	0x8e, 0xc9, 0xaa, 0xc0, 0x76, 0x3f, 0x1c, 0xd0, 0xb8, 0x90, 0xde, 0xcd, 0x58, 0xc4, 0x10, 0x0c,
	0x41, 0x55, 0xfe, 0x62, 0xcb, 0xf6, 0xed, 0xbe, 0x3b, 0xea, 0x04, 0x06, 0x2f, 0x83, 0x2b, 0x21,
	0x0b, 0xeb, 0xeb, 0xd7, 0x8e, 0xf5, 0xf4, 0xfe, 0x3c, 0xb0, 0xa7, 0xaa, 0x12, 0x9e, 0x81, 0x1a,
	0x37, 0x60, 0x82, 0x29, 0x6b, 0x7d, 0xf3, 0x2b, 0x7d, 0x77, 0xf4, 0xd7, 0xdc, 0x85, 0x50, 0x16,
	0x3a, 0xbc, 0xc7, 0x74, 0x5f, 0x04, 0xff, 0x80, 0x3a, 0x8f, 0xc7, 0x7c, 0xd0, 0x56, 0xc5, 0xb7,
	0xfb, 0xce, 0xf4, 0x2b, 0x01, 0x2f, 0x81, 0xab, 0xbc, 0x13, 0x04, 0x47, 0x10, 0x7c, 0x23, 0x61,
	0x2c, 0xb5, 0x0a, 0xa2, 0x97, 0xc2, 0x2e, 0x68, 0xa8, 0xa3, 0x44, 0x7d, 0x17, 0xa8, 0x83, 0x1c,
	0xbc, 0x06, 0x3f, 0xf5, 0x27, 0x10, 0xc8, 0xaa, 0x40, 0xf6, 0x8c, 0xc8, 0x99, 0x56, 0xa0, 0xb8,
	0x47, 0x4d, 0xe0, 0x7f, 0xd0, 0xd4, 0x73, 0x72, 0x82, 0x1f, 0x62, 0x82, 0xe3, 0x0b, 0xee, 0x29,
	0x7f, 0x5d, 0x81, 0xaf, 0x95, 0x78, 0x3a, 0xc1, 0x4b, 0x54, 0x78, 0x5a, 0x14, 0x71, 0x4f, 0x79,
	0x2c, 0x31, 0x75, 0xe9, 0xe9, 0x3e, 0xc1, 0x3d, 0x55, 0x8b, 0x21, 0x08, 0xa0, 0xc4, 0xd3, 0x73,
	0xa9, 0x2d, 0x3c, 0xd5, 0x4a, 0xb9, 0xa7, 0xea, 0x28, 0x51, 0xae, 0xf4, 0x54, 0xcf, 0x85, 0xa7,
	0xeb, 0xad, 0x67, 0x6f, 0xb6, 0x9e, 0xfd, 0xb6, 0xf5, 0xec, 0xc7, 0x9d, 0x67, 0x6d, 0x76, 0x9e,
	0xf5, 0xb2, 0xf3, 0xac, 0x9b, 0x8e, 0xbe, 0xaa, 0xf7, 0x07, 0x8b, 0xcb, 0x1e, 0x32, 0x44, 0xe7,
	0x55, 0xb1, 0xb7, 0x27, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc0, 0xd9, 0x44, 0x13, 0x0a, 0x04,
	0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AccountCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AccountCount))
		i--
		dAtA[i] = 0x58
	}
	if len(m.AccountList) > 0 {
		for iNdEx := len(m.AccountList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AccountList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.LikeCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LikeCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.LikeList) > 0 {
		for iNdEx := len(m.LikeList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LikeList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.SubscriptionCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SubscriptionCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.SubscriptionList) > 0 {
		for iNdEx := len(m.SubscriptionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SubscriptionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.CommentCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CommentCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.CommentList) > 0 {
		for iNdEx := len(m.CommentList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CommentList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.PostCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.PostCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PostList) > 0 {
		for iNdEx := len(m.PostList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PostList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PostList) > 0 {
		for _, e := range m.PostList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.PostCount != 0 {
		n += 1 + sovGenesis(uint64(m.PostCount))
	}
	if len(m.CommentList) > 0 {
		for _, e := range m.CommentList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CommentCount != 0 {
		n += 1 + sovGenesis(uint64(m.CommentCount))
	}
	if len(m.SubscriptionList) > 0 {
		for _, e := range m.SubscriptionList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.SubscriptionCount != 0 {
		n += 1 + sovGenesis(uint64(m.SubscriptionCount))
	}
	if len(m.LikeList) > 0 {
		for _, e := range m.LikeList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.LikeCount != 0 {
		n += 1 + sovGenesis(uint64(m.LikeCount))
	}
	if len(m.AccountList) > 0 {
		for _, e := range m.AccountList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.AccountCount != 0 {
		n += 1 + sovGenesis(uint64(m.AccountCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostList = append(m.PostList, Post{})
			if err := m.PostList[len(m.PostList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostCount", wireType)
			}
			m.PostCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PostCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommentList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommentList = append(m.CommentList, Comment{})
			if err := m.CommentList[len(m.CommentList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommentCount", wireType)
			}
			m.CommentCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CommentCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubscriptionList = append(m.SubscriptionList, Subscription{})
			if err := m.SubscriptionList[len(m.SubscriptionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionCount", wireType)
			}
			m.SubscriptionCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LikeList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LikeList = append(m.LikeList, Like{})
			if err := m.LikeList[len(m.LikeList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LikeCount", wireType)
			}
			m.LikeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LikeCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountList = append(m.AccountList, Account{})
			if err := m.AccountList[len(m.AccountList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountCount", wireType)
			}
			m.AccountCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccountCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
